-- USER ROLE
insert into user_role (ROLE_ID, ROLE_DESC, PARENT_ROLE_ID, STATUS, CREATEBY, MODIFYBY, REMARKS)
values ('1', 'BASIC', NULL, 'A', '81149189', '81149189','BASIC ROLE');

insert into user_role (ROLE_ID, ROLE_DESC, PARENT_ROLE_ID, STATUS, CREATEBY, MODIFYBY, REMARKS)
values ('2', 'SYS_ADMIN', NULL, 'A', '81149189', '81149189', 'System Admin');