INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY, ENCRYPT)
VALUES ('API_CLIENT', 'BES.key', 'AAAAAUzkg7UwC952iERsAyz3eE2krPK6n1tfEeShZqJnzXYUGvD99YFJfiJuBSNukbSGBny965bKjOOGg78OosGIkTbF3Fdn', 'String', sysdate, '01634476', sysdate, '01634476', 'Y');

INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY, ENCRYPT)
VALUES ('API_CLIENT', 'WFM.key', 'AAAAAUcnZFQnonr+gJ/YCGP3fn8DwvtNa7SfHtEQF/2LIpNepZtFAgnIzpOWBmVBkMuZhCVTo29yyFGO/OBqLJQZDjR6QOYo', 'String', sysdate, '01634476', sysdate, '01634476', 'Y');

INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY, ENCRYPT)
VALUES ('API_CLIENT', 'OSS.key', 'AAAAAZ5dloYpXVbtscIApsnZDiUUOmhguXGo4c5M5lOF9L8tCA46Lc0qtC5JYhbaPmvs/dUtZH1RhxFG55Poj8+IOeMa+XIR', 'String', sysdate, '01634476', sysdate, '01634476', 'Y');
