-- Site Config
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('SITE', 'givenDomain', 'yecvm-savt01.pccw.com', 'String', sysdate, 0, sysdate, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('SITE', 'cronjobHostname', 'yecvm-savt01', 'String', current_timestamp, 0, current_timestamp, 0);



insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'systemName', 'BES', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'url', 'https://10.50.68.110:1443', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'header.Authorization', 'Bearer fcb98614187cf228da1d844e787b28dd', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'header.OperatorId', '999007', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'header.X-APP-Key', 'b0025e19d6a649278cdfeb520c224ef2', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'header.BeId', '101', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_BES', 'header.ChannelType', '613', 'String', current_timestamp, 0, current_timestamp, 0);

insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_ITSM_RESTFUL', 'systemName', 'ITSM_RESTFUL', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_ITSM_RESTFUL', 'url', 'https://jecvm-itsmvt01.pccw.com/cloudrs', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_ITSM_RESTFUL', 'userName', 'sa', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_ITSM_RESTFUL', 'password', 'sa2018', 'String', current_timestamp, 0, current_timestamp, 0);

insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_ITSM', 'systemName', 'ITSM', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_ITSM', 'url', 'https://jecvm-itsmvt01.pccw.com/itsm', 'String', current_timestamp, 0, current_timestamp, 0);

insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_NORARS', 'systemName', 'NORARS', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_NORARS', 'url', 'https://norauat.oss.pccw.com', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_NORARS', 'userName', 'sd', 'String', current_timestamp, 0, current_timestamp, 0);
insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_NORARS', 'password', 'g$Hw0#MG-3', 'String', current_timestamp, 0, current_timestamp, 0);

insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_WFM', 'systemName', 'WFM', 'String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_WFM','url','https://yecvm-wfmvt01.pccw.com/wfm','String',current_timestamp,0,current_timestamp,0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_WFM','userName','sd','String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_WFM','password','Ki6/rEDs47*^5','String', current_timestamp, 0, current_timestamp, 0);

insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_UT_CALL', 'systemName', 'UT_CALL', 'String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','url','http://10.252.16.151:8080','String',current_timestamp,0,current_timestamp,0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','fid','f023000000','String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','user','SERVDESK','String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','pwd','nvng[kGZE\C^','String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','sys','servdesk','String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','seq','2','String', current_timestamp, 0, current_timestamp, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_UT_CALL','type','v1','String', current_timestamp, 0, current_timestamp, 0);


insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_OSS', 'systemName', 'OSS', 'String', sysdate, 0, sysdate, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_WFM', 'url', 'http://10.6.52.130:58080', 'String', sysdate, 0, sysdate, 0);


INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SAP_PROD', 'https://sap.pccw.com/sap', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'HKT_SDS_PROD', 'https://hkt.sds.pccw.com/hkt', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'BLIMS_SDS_PROD', 'https://blims.sds.pccw.com/blims', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'CSPORTAL_PROD', 'https://csportal.pccw.com/sp', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'APPOINTMENT_HKT_PROD', 'https://www.appointment.hkt.com', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'APPOINTMENT_HKT_UAT', 'https://uat.appointment.hkt.com', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SDP_PROD', 'https://sdp.pccw.com/sdps', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'HKT_SKYEXCHANGE_PROD', 'https://csp.hkt-skyexchange.com/skyexchange', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SHOP_HKT_SME_PROD', 'https://shop.hkt-sme.com', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SHOP_HKT_PCCW_PROD', 'https://shop.hkt.pccw.com/ospadmin', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SHOPDR_HKT_SME_PROD', 'https://shopdr.hkt-sme.com/osp', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SHOPDR_HKT_PCCW_PROD', 'https://shopdr.hkt.pccw.com/ospadmin', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SHOP01_HKT_SME_PROD', 'https://shop01.hkt-sme.com', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'SHOP01_HKT_PCCW_PROD', 'https://shop01.hkt.pccw.com/ospadmin', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'NORA_PROD', 'https://nora.oss.pccw.com/nora', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'OPG_PROD', 'https://opg.pccw.com/opg', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'WFM_PROD', 'https://wfm.pccw.com/wfm', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'HKTCLOUD_PROD', 'https://login.site.hkt-cloud.com/hktcloud', 'String', '01634476', '01634476');
INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEBY, MODIFYBY)
VALUES ('CHECK_CERT_JOB', 'ITSM_PROD', 'https://itsm.pccw.com/itsm', 'String', '01634476', '01634476');
