REM 18-MAr-2021 Create lookup for GMB Service
SET DEFINE OFF;

Insert into SD.SERVICE_TYPE (SERVICE_TYPE_CODE,SERVICE_TYPE_NAME,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','GMB',sysdate,'00496877',sysdate,'00496877');
-- 
REM INSERTING into SD.USER_ROLE

Insert into SD.USER_ROLE (ROLE_ID,ROLE_DESC,PARENT_ROLE_ID,STATUS,ABSTRACT,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('TH__E_TEAM_GMB','GMB Team Head','TEAM_HEAD','A',null,sysdate,'00496877',sysdate,'00496877','GMB Team Engineer Head');
Insert into SD.USER_ROLE (ROLE_ID,ROLE_DESC,PARENT_ROLE_ID,STATUS,ABSTRACT,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('E_TEAM_GMB',  'GMB',        'ENG',      'A',null,sysdate,'00496877',sysdate,'00496877','GMB Team Engineer');

Insert into SD.SERVICE_TYPE_USER_ROLE (ROLE_ID,SERVICE_TYPE_CODE,CREATEDATE,CREATEBY) values ('E_TEAM_GMB','GMB',sysdate,'00496877');
Insert into SD.SERVICE_TYPE_USER_ROLE (ROLE_ID,SERVICE_TYPE_CODE,CREATEDATE,CREATEBY) values ('SYS_ADMIN','GMB',sysdate,'00496877');
Insert into SD.SERVICE_TYPE_USER_ROLE (ROLE_ID,SERVICE_TYPE_CODE,CREATEDATE,CREATEBY) values ('TH__E_TEAM_GMB','GMB',sysdate,'00496877');

-- Insert into SD.SYMPTOM (SYMPTOM_CODE,SYMPTOM_DESCRIPTION,SYMPTOM_GROUP_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('CL005','Field Service Required','105',sysdate,'00496877',sysdate,'00496877');

-- Insert into SD.SYMPTOM_MAPPING (SERVICE_TYPE_CODE,SYMPTOM_CODE,CREATEDATE,CREATEBY) values ('GMB','CL005',sysdate,'00496877');
--Insert into SD.SYMPTOM_MAPPING (SERVICE_TYPE_CODE,SYMPTOM_CODE,CREATEDATE,CREATEBY) values ('GMB','CL006',sysdate,'00496877');
-- Insert into SD.SYMPTOM_MAPPING (SERVICE_TYPE_CODE,SYMPTOM_CODE,CREATEDATE,CREATEBY) values ('GMB','CL007',sysdate,'00496877');
--
Insert into SD.CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,ENCRYPT,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('SEARCH_KEY_TYPE_MAPPING','GMB','plateId','String','N',sysdate,'00496877',sysdate,'00496877');

REM INSERTING into SD.CLOSECODE
-- Insert into SD.CLOSECODE (CLOSE_CODE,CLOSE_CODE_DESCRIPTION,CREATEDATE,DISPLAY_SEQ,CREATEBY,MODIFYDATE,MODIFYBY) values ('CC006','Other GMB option',sysdate,6,'00496877',sysdate,'00496877');
REM INSERTING into SD.CLOSECODE_MAPPING

--Insert into SD.CLOSECODE_MAPPING (SERVICE_TYPE_CODE,CLOSE_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','CC001',sysdate,'00496877',sysdate,'00496877');
--Insert into SD.CLOSECODE_MAPPING (SERVICE_TYPE_CODE,CLOSE_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','CC002',sysdate,'00496877',sysdate,'00496877');
--Insert into SD.CLOSECODE_MAPPING (SERVICE_TYPE_CODE,CLOSE_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','CC006',sysdate,'00496877',sysdate,'00496877');


REM INSERTING into SD.PATH_CTRL
SET DEFINE OFF;
--Insert into SD.PATH_CTRL (PATH,STATUS,DESCRIPTION,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('/api/v1/ticket/**','A','OSS API',sydate,'00496877',sysdate,'00496877',null);
REM INSERTING into SD.USER_ROLE_PATH_CTRL
SET DEFINE OFF;
--Insert into SD.USER_ROLE_PATH_CTRL (ROLE_ID,PATH_CTRL_ID,CREATEDATE,CREATEBY,REMARKS) values ('API_OSS',91, sysdate,'00496877',null);
commit;

-- change table USER_OWNER_AUTH_ROLE_MAPPING by adding new column service_type
alter table sd.USER_OWNER_AUTH_ROLE_MAPPING add service_type_code varchar2(10);
alter table sd.USER_OWNER_AUTH_ROLE_MAPPING drop primary key;
alter table sd.USER_OWNER_AUTH_ROLE_MAPPING add primary key (OWNER_ID, service_type_code, AUTH_ROLE_ID);

REM INSERTING into SD.USER_OWNER_AUTH_ROLE_MAPPING
SET DEFINE OFF;
Insert into SD.USER_OWNER_AUTH_ROLE_MAPPING (OWNER_ID,AUTH_ROLE_ID, SERVICE_TYPE_CODE, CREATEDATE) values ('API_OSS','E_TEAM_GMB', 'GMB', sysdate);
Insert into SD.USER_OWNER_AUTH_ROLE_MAPPING (OWNER_ID,AUTH_ROLE_ID, SERVICE_TYPE_CODE, CREATEDATE) values ('API_OSS','TH__E_TEAM_GMB', 'GMB', sysdate);
commit;

REM INSERTING into SD.PATH_CTRL
SET DEFINE OFF;
Insert into SD.PATH_CTRL (PATH,STATUS,DESCRIPTION,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('/api/**','A','Common API',sysdate,'00496877',sysdate,'00496877',null);
commit;

-- redefine smart meter code

-- SYMPTOM_GROUP
INSERT INTO SYMPTOM_GROUP (SYMPTOM_GROUP_CODE, SYMPTOM_GROUP_NAME, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY) VALUES ('109', 'GMB', SYSDATE, '00496877', SYSDATE, '00496877');
commit;

INSERT INTO SYMPTOM (SYMPTOM_CODE, SYMPTOM_DESCRIPTION, SYMPTOM_GROUP_CODE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY) VALUES ('MB001', 'Need Field', '109', SYSDATE, '00496877', SYSDATE, '00496877');
INSERT INTO SYMPTOM (SYMPTOM_CODE, SYMPTOM_DESCRIPTION, SYMPTOM_GROUP_CODE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY) VALUES ('MB002', 'Need PND', '109', SYSDATE, '00496877', SYSDATE, '00496877');
INSERT INTO SYMPTOM (SYMPTOM_CODE, SYMPTOM_DESCRIPTION, SYMPTOM_GROUP_CODE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY) VALUES ('MB003', 'Need PND and Field', '109', SYSDATE, '00496877', SYSDATE, '00496877');

INSERT INTO SYMPTOM_MAPPING (SERVICE_TYPE_CODE, SYMPTOM_CODE, CREATEDATE, CREATEBY) VALUES ('GMB', 'MB001', SYSDATE, '00496877');
INSERT INTO SYMPTOM_MAPPING (SERVICE_TYPE_CODE, SYMPTOM_CODE, CREATEDATE, CREATEBY) VALUES ('GMB', 'MB002', SYSDATE, '00496877');
INSERT INTO SYMPTOM_MAPPING (SERVICE_TYPE_CODE, SYMPTOM_CODE, CREATEDATE, CREATEBY) VALUES ('GMB', 'MB003', SYSDATE, '00496877');
commit;


