REM 18-MAr-2021 Create lookup for GMB Service
SET DEFINE OFF;

Insert into SD.SERVICE_TYPE (SERVICE_TYPE_CODE,SERVICE_TYPE_NAME,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','GMB',sysdate,'00496877',sysdate,'00496877');
-- 
REM INSERTING into SD.USER_ROLE

Insert into SD.USER_ROLE (ROLE_ID,ROLE_DESC,PARENT_ROLE_ID,STATUS,ABSTRACT,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('TH__E_TEAM_GMB','GMB Team Head','TEAM_HEAD','A',null,sysdate,'00496877',sysdate,'00496877','GMB Team Engineer Head');
Insert into SD.USER_ROLE (ROLE_ID,ROLE_DESC,PARENT_ROLE_ID,STATUS,ABSTRACT,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('E_TEAM_GMB',  'GMB',        'ENG',      'A',null,sysdate,'00496877',sysdate,'00496877','GMB Team Engineer');

Insert into SD.SERVICE_TYPE_USER_ROLE (ROLE_ID,SERVICE_TYPE_CODE,CREATEDATE,CREATEBY) values ('E_TEAM_GMB','GMB',sysdate,'00496877');
Insert into SD.SERVICE_TYPE_USER_ROLE (ROLE_ID,SERVICE_TYPE_CODE,CREATEDATE,CREATEBY) values ('SYS_ADMIN','GMB',sysdate,'00496877');
Insert into SD.SERVICE_TYPE_USER_ROLE (ROLE_ID,SERVICE_TYPE_CODE,CREATEDATE,CREATEBY) values ('TH__E_TEAM_GMB','GMB',sysdate,'00496877');

-- Insert into SD.SYMPTOM (SYMPTOM_CODE,SYMPTOM_DESCRIPTION,SYMPTOM_GROUP_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('CL005','Field Service Required','105',sysdate,'00496877',sysdate,'00496877');

Insert into SD.SYMPTOM_MAPPING (SERVICE_TYPE_CODE,SYMPTOM_CODE,CREATEDATE,CREATEBY) values ('GMB','CL005',sysdate,'00496877');
Insert into SD.SYMPTOM_MAPPING (SERVICE_TYPE_CODE,SYMPTOM_CODE,CREATEDATE,CREATEBY) values ('GMB','CL006',sysdate,'00496877');
Insert into SD.SYMPTOM_MAPPING (SERVICE_TYPE_CODE,SYMPTOM_CODE,CREATEDATE,CREATEBY) values ('GMB','CL007',sysdate,'00496877');
--
Insert into SD.CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,ENCRYPT,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('SEARCH_KEY_TYPE_MAPPING','GMB','plateId','String','N',sysdate,'00496877',sysdate,'00496877');

REM INSERTING into SD.CLOSECODE
-- Insert into SD.CLOSECODE (CLOSE_CODE,CLOSE_CODE_DESCRIPTION,CREATEDATE,DISPLAY_SEQ,CREATEBY,MODIFYDATE,MODIFYBY) values ('CC006','Other GMB option',sysdate,6,'00496877',sysdate,'00496877');
REM INSERTING into SD.CLOSECODE_MAPPING

--Insert into SD.CLOSECODE_MAPPING (SERVICE_TYPE_CODE,CLOSE_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','CC001',sysdate,'00496877',sysdate,'00496877');
--Insert into SD.CLOSECODE_MAPPING (SERVICE_TYPE_CODE,CLOSE_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','CC002',sysdate,'00496877',sysdate,'00496877');
--Insert into SD.CLOSECODE_MAPPING (SERVICE_TYPE_CODE,CLOSE_CODE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY) values ('GMB','CC006',sysdate,'00496877',sysdate,'00496877');


REM INSERTING into SD.PATH_CTRL
SET DEFINE OFF;
--Insert into SD.PATH_CTRL (PATH,STATUS,DESCRIPTION,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY,REMARKS) values ('/api/v1/ticket/**','A','OSS API',sydate,'00496877',sysdate,'00496877',null);
REM INSERTING into SD.USER_ROLE_PATH_CTRL
SET DEFINE OFF;
--Insert into SD.USER_ROLE_PATH_CTRL (ROLE_ID,PATH_CTRL_ID,CREATEDATE,CREATEBY,REMARKS) values ('API_OSS',91, sysdate,'00496877',null);
commit;
REM INSERTING into SD.USER_OWNER_AUTH_ROLE_MAPPING
SET DEFINE OFF;
Insert into SD.USER_OWNER_AUTH_ROLE_MAPPING (OWNER_ID,AUTH_ROLE_ID,CREATEDATE) values ('API_OSS','E_TEAM_GMB',sysdate);
commit;

