-- User Role Path Ctrl
insert into USER_ROLE_PATH_CTRL (ROLE_ID, PATH_CTRL_ID, CREATEBY, REMARKS)
values('BASIC', 1, '81149189', 'Basic');

insert into USER_ROLE_PATH_CTRL (ROLE_ID, PATH_CTRL_ID, CREATEBY, REMARKS)
values('SYS_ADMIN', 2, '81149189', 'System Admin');

insert into USER_ROLE_PATH_CTRL (ROLE_ID, PATH_CTRL_ID, CREATEBY, REMARKS)
values('CS_AGENT', 3, '81149189', 'Fault Page');

insert into USER_ROLE_PATH_CTRL (ROLE_ID, PATH_CTRL_ID, CREATEBY, REMARKS)
values('TEAM_HEAD', 4, '81149189', 'Manager User');


