# According to arch team this may need SUPER privilege to create
# Contact: Assistant Solution Architect - Oscar.CW.Tsang@pccw.com (2888 8837)

CREATE TRIGGER CONFIG_PARAM_BEFORE_UPDATE BEFORE UPDATE ON CONFIG_PARAM
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER PATH_CTRL_BEFORE_UPDATE BEFORE UPDATE ON PATH_CTRL
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER CRON_JOB_BEFORE_UPDATE BEFORE UPDATE ON CRON_JOB
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER CRON_JOB_LOG_BEFORE_UPDATE BEFORE UPDATE ON CRON_JOB_LOG
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER NOC_COMPANY_BEFORE_UPDATE BEFORE UPDATE ON NOC_COMPANY
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;


CREATE TRIGGER NOC_USER_BEFORE_UPDATE BEFORE UPDATE ON NOC_USER
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;


CREATE TRIGGER NOC_ACCESS_REQUEST_BEFORE_UPDATE BEFORE UPDATE ON NOC_ACCESS_REQUEST
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER NOC_ACCESS_REQUEST_VISITOR_BEFORE_UPDATE BEFORE UPDATE ON NOC_ACCESS_REQUEST_VISITOR
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER NOC_ACCESS_REQUEST_EQUIP_BEFORE_UPDATE BEFORE UPDATE ON NOC_ACCESS_REQUEST_EQUIP
  FOR EACH ROW
  BEGIN
    SET NEW.CREATEDATE = OLD.CREATEDATE;
    SET NEW.CREATEBY = OLD.CREATEBY;
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;

CREATE TRIGGER NOC_ACCESS_REQUEST_HASH_BEFORE_UPDATE BEFORE UPDATE ON NOC_ACCESS_REQUEST_HASH
  FOR EACH ROW
  BEGIN
    SET NEW.MODIFYDATE = CURRENT_TIMESTAMP;
  END;