INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY, ENCRYPT)
VALUES ('API_CLIENT', 'BES.key', '', 'String', sysdate, '01634476', sysdate, '01634476', 'Y');

INSERT INTO CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY, ENCRYPT)
VALUES ('API_CLIENT', 'WFM.key', '', 'String', sysdate, '01634476', sysdate, '01634476', 'Y');