spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    jndi-name: java:comp/env/jdbc/servdesk
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

project:
  buildtime: @buildTimestamp@

