spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:oracle:thin:@10.111.14.154:1521:sdsDEV
    #sdsvt
    username: sd
    password: dwfm123
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

project:
  buildtime: #@'@buildTimestamp@'

logging:
  level:
    #    org:
    #      springframework:
    #        web: debug
    #        security: debug
    com:
      hkt:
        btu:
          sd: debug

server:
  servlet:
    context-path: /servicedesk

servicedesk:
  aesKeystore:
    path: D:\IdeaProjects\servicedesk\setup\server\keystore\non-prod\servicedesk-aes-keystore.jck
    storePass: 7284ec9a-11ab-4999-936f-7f823376bd37

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: abc
  resource: ovie-app
  public-client: false
  principal-attribute: preferred_username

