-- pre-launch
--------------------------------------------------------------------------------------------------
-- Auto Retry (re-execute certain methods)
CREATE SEQUENCE  SEQ_AUTO_RETRY_ID START WITH 1;
CREATE TABLE AUTO_RETRY
(
    RETRY_ID                NUMBER              default SEQ_AUTO_RETRY_ID.nextval,

    CLAZZ                   VARCHAR2(100)       not null,
    METHOD_NAME             VARCHAR2(50)        not null,
    METHOD_PARAM            VARCHAR2(500)       not null,

    STATUS                  VARCHAR2(2)         not null,
    TRY_COUNT               NUMBER              not null,
    MIN_WAIT_SECOND         NUMBER,
    NEXT_TARGET_TIME        DATE,

    CREATEDATE              DATE                default SYSDATE not null,
    CREATEBY                VARCHAR2(10)        not null,
    MODIFYDATE              DATE                default SYSDATE not null,
    MODIFYBY                VARCHAR2(10)        not null,
    REMARKS                 VARCHAR2(250),
    constraint AUTO_RETRY_PK primary key (RETRY_ID)
);
CREATE INDEX IDX_AUTO_RETRY_1 ON AUTO_RETRY (STATUS);
CREATE INDEX IDX_AUTO_RETRY_2 ON AUTO_RETRY (NEXT_TARGET_TIME);


CREATE OR REPLACE TRIGGER TRIGGER_AUTO_RETRY_1
    BEFORE INSERT ON AUTO_RETRY
    FOR EACH ROW
BEGIN
    :NEW.CREATEDATE := SYSDATE;
END;
/
CREATE OR REPLACE TRIGGER TRIGGER_AUTO_RETRY_2
    BEFORE UPDATE ON AUTO_RETRY
    FOR EACH ROW
BEGIN
    :NEW.CREATEDATE := :OLD.CREATEDATE;
    :NEW.CREATEBY := :OLD.CREATEBY;
    :NEW.MODIFYDATE := SYSDATE;
END;
/
--------------------------------------------------------------------------------------------------
create table SERVICE_TYPE_USER_ROLE
 (
     ROLE_ID                       VARCHAR2(20)             not null,
     SERVICE_TYPE_CODE             VARCHAR2(10)             not null,
     CREATEDATE                    DATE                     default SYSDATE not null,
     CREATEBY                      VARCHAR2(12)             not null
 );
CREATE UNIQUE INDEX IDX_SERVICE_TYPE_USER_ROLE ON SERVICE_TYPE_USER_ROLE (ROLE_ID, SERVICE_TYPE_CODE);
/
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'E_FIELD', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'E_FIELD', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('EC_365', 'E_FIELD', TO_DATE('2020-04-16 16:12:26', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'E_FIELD', TO_DATE('2020-04-16 16:11:40', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'E_FIELD', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'E_ISRC_BB', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'E_ISRC_V', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'E_ISRC_V', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'E_ISRC_V', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'O_CHL', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'O_CHL', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'O_CHL', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('EC_365', 'O_CHL', TO_DATE('2020-04-16 16:12:26', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'O_CHL', TO_DATE('2020-04-16 16:11:40', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'O_NFM', TO_DATE('2020-04-16 16:11:40', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('EC_365', 'O_NFM', TO_DATE('2020-04-16 16:12:26', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'O_USC', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'SYS_ADMIN', TO_DATE('2020-04-13 15:18:23', 'YYYY-MM-DD HH24:MI:SS'), '81209181');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'SYS_ADMIN', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'SYS_ADMIN', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('METER', 'SYS_ADMIN', TO_DATE('2020-04-14 10:46:37', 'YYYY-MM-DD HH24:MI:SS'), '81209181');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'SYS_ADMIN', TO_DATE('2020-04-13 15:22:08', 'YYYY-MM-DD HH24:MI:SS'), '81209181');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'TH__E_FIELD', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'TH__E_FIELD', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'TH__E_FIELD', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('EC_365', 'TH__E_FIELD', TO_DATE('2020-04-16 16:12:26', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'TH__E_FIELD', TO_DATE('2020-04-16 16:11:40', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'TH__E_ISRC_BB', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'TH__E_ISRC_V', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'TH__E_ISRC_V', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'TH__E_ISRC_V', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'TH__O_CHL', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('FN', 'TH__O_CHL', TO_DATE('2020-04-16 16:13:20', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('EC_365', 'TH__O_CHL', TO_DATE('2020-04-16 16:12:26', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'TH__O_CHL', TO_DATE('2020-04-16 16:11:40', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('VOIP', 'TH__O_CHL', TO_DATE('2020-04-16 16:13:51', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('E_CLOUD', 'TH__O_NFM', TO_DATE('2020-04-16 16:11:40', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('EC_365', 'TH__O_NFM', TO_DATE('2020-04-16 16:12:26', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
INSERT INTO SD.SERVICE_TYPE_USER_ROLE (SERVICE_TYPE_CODE, ROLE_ID, CREATEDATE, CREATEBY) VALUES ('BN', 'TH__O_USC', TO_DATE('2020-04-16 16:11:03', 'YYYY-MM-DD HH24:MI:SS'), '01634476');
--------------------------------------------------------------------------------------------------
-- service type search key mapping
INSERT INTO SD.CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
VALUES ('SEARCH_KEY_TYPE_MAPPING', 'BN', 'bsn,dn', 'String', sysdate, '81209181', sysdate, '81209181');
INSERT INTO SD.CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
VALUES ('SEARCH_KEY_TYPE_MAPPING', 'VOIP', 'bsn,dn', 'String', sysdate, '81209181', sysdate, '81209181');
INSERT INTO SD.CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
VALUES ('SEARCH_KEY_TYPE_MAPPING', 'E_CLOUD', 'bsn,tenantId', 'String', sysdate, '81209181', sysdate, '81209181');
INSERT INTO SD.CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
VALUES ('SEARCH_KEY_TYPE_MAPPING', 'EC_365', 'tenantId', 'String', sysdate, '81209181', sysdate, '81209181');
INSERT INTO SD.CONFIG_PARAM (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
VALUES ('SEARCH_KEY_TYPE_MAPPING', 'METER', 'poleId', 'String', sysdate, '81209181', sysdate, '81209181');

insert into CONFIG_PARAM(CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_VALUE_TYPE, CREATEDATE, CREATEBY, MODIFYDATE, MODIFYBY)
values ('API_OSS', 'systemName', 'OSS', 'String', sysdate, 0, sysdate, 0);
Insert into CONFIG_PARAM (CONFIG_GROUP,CONFIG_KEY,CONFIG_VALUE,CONFIG_VALUE_TYPE,CREATEDATE,CREATEBY,MODIFYDATE,MODIFYBY)
values ('API_OSS', 'url', 'https://10.174.1.28:58443', 'String', sysdate, 0, sysdate, 0);

-- post-launch
delete SD.CONFIG_PARAM where SD.CONFIG_PARAM.CONFIG_GROUP='API_BES' and SD.CONFIG_PARAM.CONFIG_KEY = 'userName';
delete SD.CONFIG_PARAM where SD.CONFIG_PARAM.CONFIG_GROUP='API_BES' and SD.CONFIG_PARAM.CONFIG_KEY = 'password';